---

- hosts: Raspberry_Pi # Roda o Playbook nas Pis
  become: true # Pede root
  tasks:


  - name: teste
    apt:
      name:
        - neofetch
        - btop
        - curl
      state: latest
      update_cache: yes

  - name: upgrade
    apt:
      upgrade: dist

