---

- hosts: all  # Roda o Playbook em todos os IPs do inventário
  become: true
  tasks:


  - name: teste
    package:
      name:
        - neofetch
        - btop
        - curl
      state: latest
      update_cache: yes


  
